### ISSUE TITLE
'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by jhss** [mit-han-lab/deepcompressor#34]
When I run the following python command,
```
python -m deepcompressor.app.diffusion.ptq configs/model/sdxl-turbo.yaml --output-dirname reference
```
I got the following error:

```
Traceback (most recent call last):
  File "/workspace/deepcompressor/deepcompressor/app/diffusion/ptq.py", line 371, in <module>
    main(config, logging_level=tools.logging.DEBUG)
  File "/workspace/deepcompressor/deepcompressor/app/diffusion/ptq.py", line 353, in main
    results = config.eval.evaluate(pipeline, skip_gen=config.skip_gen)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/deepcompressor/deepcompressor/app/diffusion/eval/config.py", line 188, in evaluate
    self.generate(pipeline, gen_root=gen_root)
  File "/workspace/deepcompressor/deepcompressor/app/diffusion/eval/config.py", line 165, in generate
    dataset = get_dataset(
              ^^^^^^^^^^^^
  File "/workspace/deepcompressor/deepcompressor/app/diffusion/eval/benchmarks/__init__.py", line 34, in get_dataset
    dataset = datasets.load_dataset(path, return_gt=return_gt, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/deepcompressor/lib/python3.12/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/deepcompressor/lib/python3.12/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/root/miniconda3/envs/deepcompressor/lib/python3.12/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/deepcompressor/lib/python3.12/site-packages/datasets/builder.py", line 547, in _create_builder_config
    logger.info(f"No config specified, defaulting to: {self.dataset_name}/{builder_config.name}")
                                                                           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/deepcompressor/deepcompressor/app/diffusion/ptq.py", line 379, in <module>
    raise e
  File "/workspace/deepcompressor/deepcompressor/app/diffusion/ptq.py", line 371, in <module>
    main(config, logging_level=tools.logging.DEBUG)
  File "/workspace/deepcompressor/deepcompressor/app/diffusion/ptq.py", line 353, in main
    results = config.eval.evaluate(pipeline, skip_gen=config.skip_gen)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/deepcompressor/deepcompressor/app/diffusion/eval/config.py", line 188, in evaluate
    self.generate(pipeline, gen_root=gen_root)
  File "/workspace/deepcompressor/deepcompressor/app/diffusion/eval/config.py", line 165, in generate
    dataset = get_dataset(
              ^^^^^^^^^^^^
  File "/workspace/deepcompressor/deepcompressor/app/diffusion/eval/benchmarks/__init__.py", line 34, in get_dataset
    dataset = datasets.load_dataset(path, return_gt=return_gt, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/deepcompressor/lib/python3.12/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/deepcompressor/lib/python3.12/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/root/miniconda3/envs/deepcompressor/lib/python3.12/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/deepcompressor/lib/python3.12/site-packages/datasets/builder.py", line 547, in _create_builder_config
    logger.info(f"No config specified, defaulting to: {self.dataset_name}/{builder_config.name}")
                                                                           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by Chenglin-Yang** [comment]
Did you solve it? I encountered the same problem.

**Comment by lmxyy** [comment]
Which diffusers version are you using?

**Comment by 1145284121** [comment]
> Which diffusers version are you using?
I also encountered the same error.
my diffusers is  0.30.3
pip show diffusers
Name: diffusers
Version: 0.30.3
Summary: State-of-the-art diffusion in PyTorch and JAX

**Comment by Andy0422** [comment]
> When I run the following python command,
> 
> ```
> python -m deepcompressor.app.diffusion.ptq configs/model/sdxl-turbo.yaml --output-dirname reference
> ```
> 
> I got the following error:
> 
> ```
> Traceback (most recent call last):
>   File "/workspace/deepcompressor/deepcompressor/app/diffusion/ptq.py", line 371, in <module>
>     main(config, logging_level=tools.logging.DEBUG)
>   File "/workspace/deepcompressor/deepcompressor/app/diffusion/ptq.py", line 353, in main
>     results = config.eval.evaluate(pipeline, skip_gen=config.skip_gen)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/workspace/deepcompressor/deepcompressor/app/diffusion/eval/config.py", line 188, in evaluate
>     self.generate(pipeline, gen_root=gen_root)
>   File "/workspace/deepcompressor/deepcompressor/app/diffusion/eval/config.py", line 165, in generate
>     dataset = get_dataset(
>               ^^^^^^^^^^^^
>   File "/workspace/deepcompressor/deepcompressor/app/diffusion/eval/benchmarks/__init__.py", line 34, in get_dataset
>     dataset = datasets.load_dataset(path, return_gt=return_gt, **kwargs)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/miniconda3/envs/deepcompressor/lib/python3.12/site-packages/datasets/load.py", line 2132, in load_dataset
>     builder_instance = load_dataset_builder(
>                        ^^^^^^^^^^^^^^^^^^^^^
>   File "/root/miniconda3/envs/deepcompressor/lib/python3.12/site-packages/datasets/load.py", line 1890, in load_dataset_builder
>     builder_instance: DatasetBuilder = builder_cls(
>                                        ^^^^^^^^^^^^
>   File "/root/miniconda3/envs/deepcompressor/lib/python3.12/site-packages/datasets/builder.py", line 342, in __init__
>     self.config, self.config_id = self._create_builder_config(
>                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/miniconda3/envs/deepcompressor/lib/python3.12/site-packages/datasets/builder.py", line 547, in _create_builder_config
>     logger.info(f"No config specified, defaulting to: {self.dataset_name}/{builder_config.name}")
>                                                                            ^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'name'
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "/workspace/deepcompressor/deepcompressor/app/diffusion/ptq.py", line 379, in <module>
>     raise e
>   File "/workspace/deepcompressor/deepcompressor/app/diffusion/ptq.py", line 371, in <module>
>     main(config, logging_level=tools.logging.DEBUG)
>   File "/workspace/deepcompressor/deepcompressor/app/diffusion/ptq.py", line 353, in main
>     results = config.eval.evaluate(pipeline, skip_gen=config.skip_gen)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/workspace/deepcompressor/deepcompressor/app/diffusion/eval/config.py", line 188, in evaluate
>     self.generate(pipeline, gen_root=gen_root)
>   File "/workspace/deepcompressor/deepcompressor/app/diffusion/eval/config.py", line 165, in generate
>     dataset = get_dataset(
>               ^^^^^^^^^^^^
>   File "/workspace/deepcompressor/deepcompressor/app/diffusion/eval/benchmarks/__init__.py", line 34, in get_dataset
>     dataset = datasets.load_dataset(path, return_gt=return_gt, **kwargs)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/miniconda3/envs/deepcompressor/lib/python3.12/site-packages/datasets/load.py", line 2132, in load_dataset
>     builder_instance = load_dataset_builder(
>                        ^^^^^^^^^^^^^^^^^^^^^
>   File "/root/miniconda3/envs/deepcompressor/lib/python3.12/site-packages/datasets/load.py", line 1890, in load_dataset_builder
>     builder_instance: DatasetBuilder = builder_cls(
>                                        ^^^^^^^^^^^^
>   File "/root/miniconda3/envs/deepcompressor/lib/python3.12/site-packages/datasets/builder.py", line 342, in __init__
>     self.config, self.config_id = self._create_builder_config(
>                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/miniconda3/envs/deepcompressor/lib/python3.12/site-packages/datasets/builder.py", line 547, in _create_builder_config
>     logger.info(f"No config specified, defaulting to: {self.dataset_name}/{builder_config.name}")
>                                                                            ^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'name'
> ```

same bugs @lmxyy
